sudo: required
services:
  - docker
before_install:
  - docker build -t panther/npmstart -f dockerfile.dev .
script:
 - docker run -e CI=true panther/npmstart npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "panther"
  env: "panther-env"
  bucket_name: "elasticbeanstalk-ap-south-1-541340610614"
  bucket_path:  "panther"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
