version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node.modules
      - .:/app
  test:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - /app/node.modules
      - .:/app
    command: ["npm" , "test"]
